# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: eudiw-wallet-issuer-poc release workflow

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  version-bump:
    permissions:
      contents: write
      packages: read
    secrets:
      inherit
    uses: ./.github/workflows/version-bump-changelog.yml
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for SLSA provenance
      actions: read   # Required for SLSA provenance v2
    needs: [version-bump]
    uses: ./.github/workflows/publish.yml
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets:
      inherit
    needs: [publish]
    uses: ./.github/workflows/release.yml
